# -*- mode: ruby -*-
# vi: set ft=ruby :

#created by: Silent-Mobius

Vagrant.configure("2") do |config|
  config.vm.define "fw" do |fw|
      fw.vm.box="debian/buster64"
      fw.vm.hostname="fw"
      fw.vm.network "private_network", ip: "10.0.2.20"
    end

    config.vm.define "c" do |c|
      c.vm.box="debian/buster64"
      c.vm.hostname="client"
      c.vm.network "private_network", ip: "10.0.2.21"
    end
end
