# -*- mode: ruby -*-
# vi: set ft=ruby :

#created by: Silent-Mobius

Vagrant.configure("2") do |config|
  config.vm.define "deb" do |deb|
    deb.vm.box = 'debian/buster64'
    deb.vm.network "private_network", ip: "10.0.0.4"
    deb.vm.hostname="debian"
    deb.vm.provider :virtualbox

    (0..3).each do |i|
      deb.vm.disk :disk, size: "5GB", name: "disk-#{i}"
    end

  end

  config.vm.define "rpm" do |rpm|
    rpm.vm.box = 'centos/7'
    rpm.vm.network "private_network", ip: "10.0.0.6"
    rpm.vm.hostname="centos"
    rpm.vm.provider :virtualbox

    (0..3).each do |i|
      rpm.vm.disk :disk, size: "5GB", name: "disk-#{i}"
    end

  end

end
