# -*- mode: ruby -*-
# vi: set ft=ruby :

# All Vagrant configuration is done below. The "2" in Vagrant.configure
# configures the configuration version (we support older styles for
# backwards compatibility). Please don't change it unless you know what
# you're doing.
$script = <<-SCRIPT
echo "Starting Provisioning..."
apt install -y install bind bind-utils
sleep 2 
systemctl enable --now named
SCRIPT

Vagrant.configure("2") do |config|
   config.vm.define "dns" do |dns|
      dns.vm.box="debian/buster64"
      dns.vm.hostname="dns"
      dns.vm.network "private_network", ip: "10.0.0.20"
      dns.vm.provision "shell", inline: $script
    end

    config.vm.define "dnsc" do |dnsc|
      dnsc.vm.box="debian/buster64"
      dnsc.vm.hostname="dns-client"
      dnsc.vm.network "private_network", ip: "10.0.0.21"
    end
end
