# -*- mode: ruby -*-
# vi: set ft=ruby :

#created by: Silent-Mobius

$script = <<-SCRIPT
echo "Starting Provisioning..."

SCRIPT

Vagrant.configure("2") do |config|
    config.vm.define "net" do |n|
        n.vm.box="debian/buster64"
        n.vm.hostname="networksrv"
        n.vm.network "private_network", ip: "10.5.0.10"
        n.vm.provision "shell", inline: $script
      end
end