# -*- mode: ruby -*-
# vi: set ft=ruby :

#created by: Silent-Mobius

  $script = <<-SCRIPT
  echo "Starting Provisioning..."
  apt install -y mdadm
  SCRIPT


  Vagrant.configure("2") do |config|
     config.vm.define "raid" do |r|
        r.vm.box="debian/buster64"
        r.vm.hostname="raidserver"
        r.vm.network "private_network", ip: "10.100.0.5"
        r.vm.provision "shell", inline: $script
      end
end
