version: '3'
services:
  flask-example:
    build: .
    volumes:
      - .:/opt
    networks:
      - ntw
  nginx:
    image: "nginx:1.18"
    ports:
      - "8080:80"
    volumes:
      - ./conf.d:/etc/nginx/conf.d
    networks:
      - ntw
    depends_on: 
      - flask-example
networks:
  ntw:
    driver: bridge
