apiVersion: v1
kind: Service
metadata:
  name: ngine
  labels:
    run: ngine
  namespace: default
spec:
  type: LoadBalancer
  ports:
  - port: 80
    targetPort: 8080
    protocol: TCP
    name: http
  selector:
    run: ngine
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: ngine
  namespace: default
spec:
  selector:
    matchLabels:
      app: ngine
  replicas: 1
  template:
    metadata:
      labels:
        app: ngine
    spec:
      containers:
      - name: ngine
        image: kuzishai/ngine-test:1.3
        ports:
        - containerPort: 8085