# -*- mode: ruby -*-
# vi: set ft=ruby :

# All Vagrant configuration is done below. The "2" in Vagrant.configure
# configures the configuration version (we support older styles for
# backwards compatibility). Please don't change it unless you know what
# you're doing.

$script4 = <<-SCRIPT
echo "Starting Provisioning..."

SCRIPT
  $script3 = <<-SCRIPT
  echo "Starting Provisioning..."

  SCRIPT

  $script2 = <<-SCRIPT
  echo "Starting Provisioning..."

  SCRIPT

  $script = <<-SCRIPT
  echo "Starting Provisioning..."

  SCRIPT


###############################################################################


Vagrant.configure("2") do |config|
    config.vm.define "iscsi" do |iscsi|
       iscsi.vm.box="debian/buster64"
       iscsi.vm.hostname="storageclient"
       iscsi.vm.network "private_network", ip: "10.0.0.53"
       iscsi.vm.provision "shell", inline: $script4
     end
     config.vm.define "storage" do |storage|
        storage.vm.box="debian/buster64"
        storage.vm.hostname="storageclient"
        storage.vm.network "private_network", ip: "10.0.0.52"
        storage.vm.provision "shell", inline: $script3
        storage.vm.provider :virtualbox
	         (0..2).each do |i|
		    storage.vm.disk :disk, size: "2GB", name: "disk-#{i}"
	      end
      end

      config.vm.define "str" do |str|
        str.vm.box="debian/buster64"
        str.vm.hostname="storagesrv"
        str.vm.network "private_network", ip: "10.0.0.51"
        str.vm.provision "shell", inline: $script2
        str.vm.provider :virtualbox
	        (0..2).each do |i|
	      str.vm.disk :disk, size: "2GB", name: "disk-#{i}"
	      end
      end
      config.vm.define "str2" do |str2|
        str2.vm.box="debian/buster64"
        str2.vm.hostname="storagesrv"
        str2.vm.network "private_network", ip: "10.0.0.50"
        str2.vm.provision "shell", inline: $script
        str2.vm.provider :virtualbox
	        (0..2).each do |i|
	      str2.vm.disk :disk, size: "2GB", name: "disk-#{i}"
      	  end
      end
end
