# -*- mode: ruby -*-
# vi: set ft=ruby :

#created by: Kuzilnx


$web_script = <<-SCRIPT
echo "starting ansible provisioning"


SCRIPT

Vagrant.configure("2") do |config|
  config.vm.provider :libvirt do |libvirt|
    libvirt.memory = 1024
    libvirt.cpu_mode = "host-model"
    libvirt.qemu_use_session = false
    libvirt.random :model => 'random'
  end
  config.vm.define "ans" do |ans|
     ans.vm.box="generic/centos7"
     ans.vm.hostname="centos-flask-app"
     ans.vm.network "private_network", ip: '192.168.100.101'
     ans.vm.network :private_network, :ip => "172.28.128.101", :mac => "525400423d57"
     ans.vm.network "forwarded_port", guest: 80, host: 8080
     ans.vm.provision "shell", path: "provision.sh"
   end
end
